version: '3.6'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/directory_analyzer_dev
      PGDATABASE: directory_analyzer_dev
      URL: localhost
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    
  
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata:
      
